openapi: 3.0.3
info:
  title: Mi Empresa API
  version: 1.0.0

paths:
  /users:
    $ref: './paths/users.yaml'
  /clients:
    $ref: './paths/clients.yaml'

components:
  schemas:
    User:
      $ref: './schemas/user.yaml'
    Client:
      $ref: './schemas/client.yaml'
